### ISSUE TITLE
Properties window is empty

### ISSUE THREAD

**Issue by NatoBoram** [Siderus/Orion#124]
**Describe the bug**
> A clear and concise description of what the bug is.

The *properties* window is empty.

**To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

1. Upload a file using the client
2. Properties window pops-up, but it's empty

**Expected behavior**
> A clear and concise description of what you expected to happen.

The properties window shouldn't be empty.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![GIF](https://user-images.githubusercontent.com/10495562/40824083-c4ae5fc0-6540-11e8-8d16-867b4780e950.gif)

**Desktop (please complete the following information):**
* Windows 10 1803
* Firefox 61.0b10 (64 bits)

**Additional context**
> Add any other context about the problem here.

* Using my own node.
* Tested with the following hash : [QmcJXUSWC2DeeEJWrGnB85CzZ7xENsAAhQ8ky4RpjHQoes](https://ipfs.io/ipfs/QmcJXUSWC2DeeEJWrGnB85CzZ7xENsAAhQ8ky4RpjHQoes)
* Providing this one for testing purpose : [QmSgM7LuscGsDn1T8eYS4qw3fhbcqHc1KX2N9X1AgE3Hsc](http://127.0.0.1:8080/ipfs/QmSgM7LuscGsDn1T8eYS4qw3fhbcqHc1KX2N9X1AgE3Hsc/2018-06-01_02-01-10.gif)

**Comment by koalalorenzo** [comment]
A good way to notice why would be to check the console:

1. open the property window
2. From the menu click on View -> Toggle Developer Tools (alternatively press cmd/ctrl + alt/option + I )
3. Click on console logs.

We have not received any issue on the issue tracker.
Are you, in case able to run it from the source code? 
We are planning new release soon, and there were some changes in the flow for adding files.

**Comment by koalalorenzo** [comment]
@NatoBoram which version of go-ipfs are you running in background? I see you have an empty list: it could be related to API version

**Comment by NatoBoram** [comment]
I was running `ipfs version 0.4.14`. After updating to `ipfs version 0.4.15`, the behaviour is still the same. 

There's absolutely nothing in the console : 

![2018-06-01_02-18-38](https://user-images.githubusercontent.com/10495562/40825025-5358c53c-6544-11e8-8d74-b445d1caf91c.gif)

I'm currently installing the dependencies on [WSL](https://www.microsoft.com/store/productId/9N9TNGVNDL3Q) to build it.

**Comment by koalalorenzo** [comment]
what if you use the included `go-IPFS`?

**Comment by NatoBoram** [comment]
Looks like it works with the included node.

Does it use my local storage at `$IPFS_PATH`?

**Comment by koalalorenzo** [comment]
Yes, for compatibility reason of the repository (the way each IPFS version handles the repository) we use a different path. 

In the future version we can customize this, but Orion needs to modify the configuration in order to work properly!

**Comment by koalalorenzo** [comment]
@NatoBoram Could you check if in the latest release this has been fixed? :) 

Thanks

**Comment by NatoBoram** [comment]
Using version 0.6.0 and IPFS version 0.4.15 : 

![2018-06-02_12-42-46](https://user-images.githubusercontent.com/10495562/40878700-b0d618bc-6662-11e8-8885-e58acc64584c.gif)

**Comment by koalalorenzo** [comment]
I just noticed that you are inspecting the console from the Storage window. What if you inspect the console of the Property window? (after adding the file) 
In case there are no logs there, you could also hit `cmd/ctrl-R` to refresh the view :)

**Comment by NatoBoram** [comment]
```json
  "Addresses": {
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Announce": [],
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "NoAnnounce": [],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001"
    ]
  }
```

I just added an exception for Orion to the firewall, and nothing different happens. One thing I'm doing that might be unusual is that I'm running IPFS from a scheduled task. This means I don't have an IPFS console running in the foreground, but the program still runs on my machine, and other applications can still connect to the node.

You can reproduce the set-up with these files.
[IPFS.zip](https://github.com/Siderus/Orion/files/2065230/IPFS.zip) : `IPFS.xml` | `ipfs.bat`

However, even when I `ipfs shutdown` my background task and re-start it with `ipfs daemon`, Orion still doesn't connect. It would be insightful to have some logs in the console, but it remains empty.

**Comment by 0x6431346e** [comment]
Hello @NatoBoram, from what I can see in the gif you provided, Orion cannot connect to the API to fetch the list of pinned items either, I'm quite surprised you are able to upload files (and that it went past the loading window, which talks to the api and gets the binary version). Since I'm not able to reproduce this (I tried it on Windows, running my own node), it's quite difficult to tell what is happening.

I've pushed some extra error handling on the branch `bugfix/159-existing-api-is-unresponsive`. Could you please try this custom build or build it yourself from the said branch?

https://siderus.io/ipfs/QmRhX56iZD8XPXvUe1tMKpAF1jGjtz5bFqLXuLgcSVpFeh

**Comment by koalalorenzo** [comment]
@NatoBoram Is it working with the custom build? :) Let us know, so we can help you!

**Comment by NatoBoram** [comment]
I'm having a hard time to download `QmRhX56iZD8XPXvUe1tMKpAF1jGjtz5bFqLXuLgcSVpFeh` and to build Orion from sources on both Windows 10 and WSL. In the meantime, I tried v0.6.1 and the issue is still there.

One thing I noticed is the Orion client will eventually get info from the IPFS node if I let the client open for a few hours, but will lose it when I close the window.

**Comment by koalalorenzo** [comment]
How big is the repository that you are managing when you select "use the existing IPFS instance"?
That used to be a problem for me: I was using IPFS with quiet some files saved and the API response was very slow.

**Comment by NatoBoram** [comment]
My IPFS folder is 12.3 GB. I think this *might* be the problem 😆

**Comment by koalalorenzo** [comment]
That would explain why the Storage Window (the main window) takes time to show information :D 
I will report this to `go-ipfs` :)

**Comment by koalalorenzo** [comment]
@NatoBoram could you have a look at: https://github.com/ipfs/go-ipfs/issues/5163#issuecomment-401078863 ?

**Comment by koalalorenzo** [comment]
No feedback, should I close this? ⏲

**Comment by NatoBoram** [comment]
Oh, yeah, it's been a long time and I reinstalled my system since. Works fine on Ubuntu with a small storage using Btrfs, but we'll have to test it again on Windows 10 with >10 GB storage.
