### ISSUE TITLE
Fetching latest Interface Version...

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#218]
Ever since the 1.0.5 beta, Orion simply never gets past the "Fetching latest Interface Version" prompt. I've had the program running now for over 6 hours, and it is still at that stage of startup. 

If possible, could you please include the latest version of the interface with each major release, with a prompt at startup that allows the user to skip downloading the latest version of the interface until program reboot, because for as long as Orion is trying to download the latest version of the interface, I'm effectively locked out of browsing my files until it finishes, if and when it finishes...

Edit: Just realised that the same thing happens when I lose internet connection. Same issue and solution applies; Please add a "Trouble connecting? Continue without connecting" button so people can access their stored files in case they lose connection to the internet.

**Comment by TheChiefMeat** [comment]
What do I do once I've got it pinned? Is there any way I can manually install the latest UI so I can get to my files?

**Comment by koalalorenzo** [comment]
Pinning is the way to manually install it locally. Once it is pinned, you can start Orion normally and keep the ipfs daemon running (it will switch to it automatically at startup). 
If it is pinned, it should fetch way faster :-) 

We are adding the "use included interface" on next release

**Comment by TheChiefMeat** [comment]
I get "Failed to fetch" error after pinning.

**Comment by koalalorenzo** [comment]
Do you have `go-ipfs` running in background or are you using Orion's node?
You should keep `go-ipfs` daemon running in background after you pinned the content

In case the problemi is somewhere else. It could be a firewall issue (blocking 53, 4001 and 5001 could be it).

**Comment by TheChiefMeat** [comment]
Yeah I have go-ipfs running in the background. Added your peers to the swarm and bootstrapped them, but I get that error once I get to Orions main screen,

Also would be nice if you could release the .html UI as a seperate downloadable app for people using the go-ipfs program, so they have a nice, clean way of interfacing with go-ipfs, but I guess that's another whole idea.

**Comment by koalalorenzo** [comment]
Check it: http://siderus.io/ipns/beta.orion.siderus.ipfs.rocks :D 
It works on browser too (by design) but it is lacking some features.

Meanwhile, can you share with us the logs? (maybe privately on Matrix chat)
The log file is available here:

- on Linux: `~/.config/Siderus Orion/log.txt`
- on OS X: `~/Library/Application\ Support/Siderus\ Orion/log.txt`
- on Windows: `%USERPROFILE%\AppData\Roaming\Siderus Orion\log.txt`

**Comment by TheChiefMeat** [comment]
Just tried it in browser, and I get "Error: XHR error" instead, not really sure what's going on there. Tried the linked CORS fix, but it didn't do anything for me either.

**Comment by TheChiefMeat** [comment]
Logs for go-ipfs daemon are:

> [2018-12-21 07:11:24.944] [info] [App] Ready
[2018-12-21 07:11:25.032] [info] Checking for updates...
[2018-12-21 07:11:25.082] [info] [App] Starting daemon connections
[2018-12-21 07:11:26.053] [debug] [getAPIVersion]
[2018-12-21 07:11:26.085] [warn] [shouldStartDaemon] Existing IPFS API on localhost:5001 has been detected
[2018-12-21 07:11:26.086] [info] [shouldStartDaemon] REPO_MIGRATIONS_BINARY_PATH C:\Program Files\Siderus Orion\resources\app.asar/fs-repo-migrations/fs-repo-migrations.exe
[2018-12-21 07:11:26.086] [info] [shouldStartDaemon] IPFS_BINARY_PATH ipfs
[2018-12-21 07:11:26.086] [info] [shouldStartDaemon] IPFS_MULTIADDR_API /ip4/127.0.0.1/tcp/5001
[2018-12-21 07:11:26.086] [info] [shouldStartDaemon] IPFS_MULTIADDR_GATEWAY /ip4/127.0.0.1/tcp/8080
[2018-12-21 07:11:26.086] [info] [shouldStartDaemon] IPFS_MULTIADDR_SWARM [ '/ip4/0.0.0.0/tcp/4001', '/ip6/::/tcp/4001' ]
[2018-12-21 07:11:26.089] [info] [shouldStartDaemon] IPFS_REPO_PATH 
[2018-12-21 07:11:26.090] [debug] [App] Fetching edge nodes of Siderus Network
[2018-12-21 07:11:26.090] [warn] [shouldStartDaemon] IPFS Daemon already running
[2018-12-21 07:11:26.294] [debug] [App] Connecting to Siderus Network
[2018-12-21 07:11:46.494] [debug] [App] Fetching CID for latest SPA
[2018-12-21 07:11:46.514] [info] [App] Latest SPA version: /ipfs/QmYtXyQh4tpbhddTSdKtGLZFWMXQtW448FnYwBZP6HjmtP
[2018-12-21 07:11:46.515] [debug] [App] Fetching Dag for: /ipfs/QmYtXyQh4tpbhddTSdKtGLZFWMXQtW448FnYwBZP6HjmtP
[2018-12-21 07:11:46.546] [info] [App] Loading the Main Window
[2018-12-21 07:11:47.187] [info] [App] The SPA is ready

**Comment by TheChiefMeat** [comment]
Log for Orion on it's own without go-ipfs is:

> [2018-12-21 07:14:27.182] [info] [App] Ready
[2018-12-21 07:14:27.271] [info] Checking for updates...
[2018-12-21 07:14:27.322] [info] [App] Starting daemon connections
[2018-12-21 07:14:30.287] [debug] [getAPIVersion]
[2018-12-21 07:14:31.314] [error] API not available Error: connect ECONNREFUSED 127.0.0.1:5001
[2018-12-21 07:14:31.314] [info] [shouldStartDaemon] IPFS_BINARY_PATH C:\Program Files\Siderus Orion\resources\app.asar/go-ipfs/ipfs.exe
[2018-12-21 07:14:31.315] [info] [shouldStartDaemon] REPO_MIGRATIONS_BINARY_PATH C:\Program Files\Siderus Orion\resources\app.asar/fs-repo-migrations/fs-repo-migrations.exe
[2018-12-21 07:14:31.315] [info] [shouldStartDaemon] IPFS_MULTIADDR_API /ip4/127.0.0.1/tcp/5001
[2018-12-21 07:14:31.320] [info] [shouldStartDaemon] IPFS_REPO_PATH C:\Users\TheChiefMeat\AppData\Roaming\Siderus Orion\ipfs-repo
[2018-12-21 07:14:31.316] [info] [shouldStartDaemon] IPFS_MULTIADDR_SWARM [ '/ip4/0.0.0.0/tcp/4001', '/ip6/::/tcp/4001' ]
[2018-12-21 07:14:31.321] [info] [prepare] Preparing and starting the daemon
[2018-12-21 07:14:31.316] [info] [shouldStartDaemon] IPFS_MULTIADDR_GATEWAY /ip4/127.0.0.1/tcp/8080
[2018-12-21 07:14:31.321] [debug] [ensurePortNotTaken]
[2018-12-21 07:14:31.329] [debug] [isIPFSInitialised] C:\Users\TheChiefMeat\AppData\Roaming\Siderus Orion\ipfs-repo\config
[2018-12-21 07:14:31.331] [debug] [Daemon] Running "C:\Program Files\Siderus Orion\resources\app.asar/fs-repo-migrations/fs-repo-migrations.exe -y" { env:
   { IPFS_PATH:
      'C:\\Users\\TheChiefMeat\\AppData\\Roaming\\Siderus Orion\\ipfs-repo' } }
[2018-12-21 07:14:31.330] [debug] [ensureRepoMigrated]
[2018-12-21 07:14:31.330] [info] [prepare] Checking the IPFS repository
[2018-12-21 07:14:31.654] [debug] [ensureDaemonConfigured]
[2018-12-21 07:14:31.653] [debug] [Daemon] Completed "C:\Program Files\Siderus Orion\resources\app.asar/fs-repo-migrations/fs-repo-migrations.exe": ipfs migration: already at or above target version number

[2018-12-21 07:14:31.653] [info] [prepare] Configuring IPFS daemon
[2018-12-21 07:14:31.690] [info] [prepare] IPFS Daemon: Starting
[2018-12-21 07:14:31.691] [debug] [startIPFSDaemon]
[2018-12-21 07:14:31.692] [debug] [SpawnIPFSCmd] C:\Program Files\Siderus Orion\resources\app.asar/go-ipfs/ipfs.exe [ 'daemon',
  '--init',
  '--enable-pubsub-experiment',
  '--api=/ip4/127.0.0.1/tcp/5001' ] { env:
   { IPFS_PATH:
      'C:\\Users\\TheChiefMeat\\AppData\\Roaming\\Siderus Orion\\ipfs-repo' } }
[2018-12-21 07:14:32.736] [debug] [startIPFSDaemon] Logging IPFS Daemon logs in: C:\Users\THECHI~1\AppData\Local\Temp\tmp-105246bFn2pxBoFGR.tmp
[2018-12-21 07:14:32.737] [debug] [ensureAPIReady]
[2018-12-21 07:14:32.736] [info] Waiting for the API to be ready
[2018-12-21 07:14:32.804] [debug] [startIPFSDaemon] IPFS Daemon: Initializing daemon...
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/windows
Golang version: go1.11.1

[2018-12-21 07:14:32.851] [debug] [startIPFSDaemon] IPFS Daemon: Swarm listening on /ip4/10.0.75.1/tcp/4001
Swarm listening on /ip4/10.1.10.6/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.20.33.225/tcp/4001
Swarm listening on /ip4/192.168.1.11/tcp/4001
Swarm listening on /ip4/192.168.56.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit

[2018-12-21 07:14:32.860] [debug] [startIPFSDaemon] IPFS Daemon: Swarm announcing /ip4/10.0.75.1/tcp/4001
Swarm announcing /ip4/10.1.10.6/tcp/4001
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.20.33.225/tcp/4001
Swarm announcing /ip4/192.168.1.11/tcp/4001
Swarm announcing /ip4/192.168.56.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (writable) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

[2018-12-21 07:14:33.738] [debug] [getAPIVersion]
[2018-12-21 07:14:34.739] [debug] [getAPIVersion]
[2018-12-21 07:14:35.739] [debug] [getAPIVersion]
[2018-12-21 07:14:36.739] [debug] [getAPIVersion]
[2018-12-21 07:14:37.740] [debug] [getAPIVersion]
[2018-12-21 07:14:38.740] [debug] [getAPIVersion]
[2018-12-21 07:14:39.740] [debug] [getAPIVersion]
[2018-12-21 07:14:40.740] [debug] [getAPIVersion]
[2018-12-21 07:14:41.741] [debug] [getAPIVersion]
[2018-12-21 07:14:42.742] [debug] [getAPIVersion]
[2018-12-21 07:14:43.742] [debug] [getAPIVersion]
[2018-12-21 07:14:44.742] [debug] [getAPIVersion]
[2018-12-21 07:14:45.744] [debug] [getAPIVersion]
[2018-12-21 07:14:46.743] [debug] [getAPIVersion]
[2018-12-21 07:14:47.743] [debug] [getAPIVersion]
[2018-12-21 07:14:48.744] [debug] [getAPIVersion]
[2018-12-21 07:14:49.745] [debug] [getAPIVersion]
[2018-12-21 07:14:50.746] [debug] [getAPIVersion]
[2018-12-21 07:14:51.745] [debug] [getAPIVersion]
[2018-12-21 07:14:52.746] [debug] [getAPIVersion]
[2018-12-21 07:14:53.747] [debug] [getAPIVersion]
[2018-12-21 07:14:54.747] [debug] [getAPIVersion]
[2018-12-21 07:14:54.749] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:14:54.749] [info] [prepare] IPFS Daemon: Started
[2018-12-21 07:14:55.757] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:14:56.749] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:14:56.750] [debug] [App] Fetching edge nodes of Siderus Network
[2018-12-21 07:14:56.937] [debug] [App] Connecting to Siderus Network
[2018-12-21 07:14:57.753] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:14:58.752] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:14:59.751] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:00.750] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:01.757] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:02.751] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:03.751] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:04.758] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:05.751] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:06.755] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:07.753] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:08.756] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:09.765] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:10.759] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:11.756] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:12.754] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:13.756] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:14.755] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:15.757] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001
[2018-12-21 07:15:18.630] [error] Error: connect ETIMEDOUT 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[2018-12-21 07:15:18.632] [error] Error: connect ETIMEDOUT 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[2018-12-21 07:15:18.632] [error] Error: connect ETIMEDOUT 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[2018-12-21 07:15:18.645] [error] Error: connect ETIMEDOUT 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
[2018-12-21 07:15:20.646] [debug] [App] Fetching CID for latest SPA
[2018-12-21 07:15:41.652] [error] [App] Failed to start Siderus Orion: Error: connect ETIMEDOUT 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)

**Comment by koalalorenzo** [comment]
About the CORS:
Once you have enabled them you need to restart `go-ipfs`.

About the logs with IPFS already running:
The App is fetching correctly, probably there is some other error that we should catch. I am going to test this later today. I have an idea or two

About the logs with Orion's own IPFS:
It looks that IPFS is slower than Orion in starting 😅 
I think a sleep of 5 seconds will help in those cases

**Comment by koalalorenzo** [comment]
Forgot to say: thank you SO MUCH, this is helping A LOT! 🎊

**Comment by TheChiefMeat** [comment]
No worries, I like helping :)

I actually restart go-ipfs a few times, and it didn't seem to do anything, could be because my node is on another computer and not on localhost? I'm running the go-ipfs program on a single board computer, and if I can, I'd like to be able to use the Orion interface with that.

**Comment by TheChiefMeat** [comment]
Scratch that, getting the same Error: XHR error on localhost too...welp

**Comment by koalalorenzo** [comment]
We just delivered the two new quick fix that are marked. Those should be available in your client within 5 minutes.

You can verify that in the About page, the UI version is `v1.0.5.1-beta`

**Comment by koalalorenzo** [comment]
Internal tracking: 
https://gitlab.com/siderus/orion/electron-shell/issues/34

**Comment by koalalorenzo** [comment]
We have just published the new beta version that adds a button to skip fetching latest version and used the included one!

Please download it from: https://orion.siderus.io/#/beta

Let me know, in case I will close this in few days

**Comment by TheChiefMeat** [comment]
Thanks for adding the skip button :)

There seems to be some sort of error with the temp go-ipfs file, I constantly get 

`[2018-12-25 16:06:30.783] [error] API not available Error: connect ETIMEDOUT 127.0.0.1:5001`

I've tried turning off my firewall but it doesn't seem to fix the issue, any ideas?

**Comment by koalalorenzo** [comment]
you should see in the log file the logs coming from `go-IPFS` as well. If those logs are before that line then there should be some configuration error in the `go-IPFS` configuration.

Those logs are normal when the app is waiting for the IPFS node to start. If the app works properly even if that line is in the logs, there is nothing to worry about :-)
