### ISSUE TITLE
Web Interface On Local Area Network Behind VPN

### ISSUE THREAD

**Issue by TheChiefMeat** [Siderus/Orion#219]
So I've been testing the web interface for the last few days, and I'm having trouble with the web interface when using it on my LAN.

I have go-ipfs set up on a small computer, and I can access it through any other computer just fine, however the Orion interface keeps getting "Error: Requested timeout" errors, and fails to add new files, make IPNS names, etc.

The API and gateway are both listening on 0.0.0.0, so I shouldn't have any issues adding files to go-ipfs. 

In the Orion UI, I have the API and Gateway set to the LAN address of 192.168.1.234, with their respective ports.

My VPN is set up to allow access to local connections (I'm using PIA), but even that doesn't work, despite the Web UI made at https://github.com/ipfs-shipyard which works perfectly.

Any ideas why this might be the case?

Edit: I get the feeling this might be some sort of DNS issue. Whenever I completely disconnect my VPN, everything is fine.

**Comment by koalalorenzo** [comment]
I am sorry you found this error. There was a bug related to IPNS keys taking long time loading. We released few minutes ago, `1.0.5.2-beta` that includes a fix for IPNS resolving issue. We also changed the `Request Timeout` error so that it includes the actual _call_ that causes the timeout.

In case that was not the error, I am currently in Italy and I am accessing my home computer using a VPN on a server (OpenVPN). Siderus Orion seems to work fine when I am connecting remotely for me, I am not sure to be honest. I am testing always with Chrome, Firefox and Safari to be sure.

My suggestion would be: can you try the new version? If the error persist, could you share the browser's console logs?

**Comment by TheChiefMeat** [comment]
I'm getting:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mixpanel.com/track?ip=0&verbose=0&data=eyJldmVudCI6InZpZXcvc3RvcmFnZSIsInByb3BlcnRpZXMiOnsiZGlzdGluY3RfaWQiOiJlZGY2OTRiNC00OTE1LTQ1MmItYTdiMi1jNmU4YjdmODY4YTIiLCJ2ZXJzaW9uIjoiMS4wLjUuMi1iZXRhIiwidG9rZW4iOiI3NmNjNTgyMTU5NGY5YzgzZDBiMThlOGI0YWEyMmVjNiIsIm1wX2xpYiI6Im5vZGUifX0%3D. (Reason: CORS request did not succeed).[Learn More]
[Worker] Tracking Error: 
Array [ "Error: XHR error" ]`

`Error: Requested timeout pin/ls main.a9b1e082094780cef277.js:1:12830
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://8e603541-4041-4dc5-b5b6-ca20af9fb003/contentscript.js
Source Map URL: ../sourcemaps/contentscript.js.map[Learn More]`

`Error: Requested timeout pin/ls main.a9b1e082094780cef277.js:1:12830
[Worker][Activity] {"timestamp":"2018-12-22T23:16:35.724Z","uuid":"7770ed05-0534-458c-8aaa-d1ded210a6a8","name":"Perspective_view_of_Korolev_crater.tif","status":"in progress","type":"file/add"}`


in the console for Firefox.

Looks like it might be another CORS issue, I'll see if I can fix it.

**Comment by TheChiefMeat** [comment]
I have:

>   "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },

and I still get the XHR Error. Is that everything I need to get the Orion UI to work correctly with CORS enabled? Because it still doesn't work despite having the above.

**Comment by TheChiefMeat** [comment]
Also just noticed that all the buttons in the settings menu are now invisible with the latest UI update.

**Comment by koalalorenzo** [comment]
Are you loading the UI from HTTPS? That could be the problem! 

http://siderus.io/ipns/beta.orion.siderus.ipfs.rocks/ will work fine 👍 

About the fix/cors we are going to publish the source code on release and we will include the QuickFix link to them. The current QuickFix link in the app is pointing to a StackOverflow

**Comment by TheChiefMeat** [comment]
Latest version seems to of fixed the buttons.

**Comment by koalalorenzo** [comment]
Is using HTTP solving the issue?

**Comment by TheChiefMeat** [comment]
Seems to be, I'm not really sure what caused the invisible button issue before, but I wasn't using https then either.

**Comment by koalalorenzo** [comment]
We have actually pushed a new version that should fixes some bugs and it might have fixed yours as well. In any case we are working to full offline support to finish 1.0 as we spoke in #218 😄 

Should we close this issue? In case you don't have this issue anymore I will close it in few days

**Comment by TheChiefMeat** [comment]
I still can't get this UI to work across my LAN with my VPN on, it could be a me issue on my network. I'll keep the issue open for now and see if I can fix it on my end.

**Comment by koalalorenzo** [comment]
Let me know what you discover! it seems very weird as it works for me 😮

**Comment by koalalorenzo** [comment]
Let me know what you discover! it seems very weird as it works for me 😮 
Maybe a better investigation should be done.

If you have the error again, please click the button to report it and add a comment that you were using VPN connection!

**Comment by koalalorenzo** [comment]
Closing down as a fix was provided! 
Please reopen if the error persist! :)
